version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - "PGDATA=/var/lib/postgresql/data"
  web:
    build: .
    environment:
      - RAILS_ENV=development
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e production
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
